recipe: default.v1
language: en

pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    type: "huggingface_hub"
    repo_id: "meta-llama/Meta-Llama-3.1-8B-Instruct"
    task: "text-generation"
  
  flow_retrieval:
      active: false

  embeddings:
    type: "huggingface_hub"
    repo_id: "BAAI/bge-large-en-v1.5"
    task: "feature-extraction"

policies:
- name: FlowPolicy
  llm:
    type: "huggingface_hub"
    repo_id: "mistralai/Mistral-7B-Instruct-v0.3"
    task: "text-generation"

  embeddings:
    type: "huggingface_hub"
    repo_id: "BAAI/bge-large-en-v1.5"
    task: "feature-extraction"

- name: IntentlessPolicy
  llm:
    type: "huggingface_hub"
    repo_id: "meta-llama/Meta-Llama-3.1-8B-Instruct"
    task: "text-generation"

  embeddings:
    type: "huggingface_hub"
    repo_id: "BAAI/bge-large-en-v1.5"
    task: "feature-extraction"

- name: EnterpriseSearchPolicy
  llm:
    type: "huggingface_hub"
    repo_id: "meta-llama/Meta-Llama-3.1-8B-Instruct"
    task: "text-generation"
  
  embeddings:
    type: "huggingface_hub"
    repo_id: "BAAI/bge-large-en-v1.5"
    task: "feature-extraction"

assistant_id: 20240807-131300-ornery-dolce
